config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get "about", to: "pages#about"
  get 'profile', to: 'pages#profile', as: :profile
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :places do
    resources :reviews, except: [:index]
  end

  resources :users, only: [:show]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  has_one_attached :header_photo
  has_many :reviews
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model

  pg_search_scope :search_by_name_and_details,
    against: [ :name, :details, :address ],
    using: {
      tsearch: { prefix: true }
    }
  scope :top, -> { joins(:reviews).order(rating: :desc) }


  def avg_review
    return "no reviews" if reviews.empty?
    reviews.average(:rating).round(2)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :place

  validates :rating, presence: true
  validates :restroom_rating, presence: true
  validates :parking_rating, presence: true
  validates :other_rating, presence: true
  validates :comment, presence: true, length: { maximum: 400 }
  delegate :first_name, to: :user, prefix: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :places
  has_many :reviews, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about]

  def home
    @places = Place.top.first(5)
    @places.each do |place|
      @reviews = Review.where(place_id: place.id).order("created_at DESC")
      if @reviews.blank?
        @avg_review = 0
      else
        @avg_review = @reviews.average(:rating).round(2)
      end
    end
  end

  def profile
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @places = Place.search_by_name_and_details(params[:query])
    else
      @places = Place.all
    end

    # @markers = @places.geocoded.map do |place|
    #   {
    #     lat: place.latitude,
    #     lng: place.longitude,
    #     info_window_html: render_to_string(partial: "info_window", locals: { place: place})
    #     marker_html: render_to_string(partial: "marker", locals: { place: place})
    #   }
    # end
  end

  def show
    @reviews = Review.where(place_id: @place.id).order("created_at DESC")
    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end

    @markers = [
      {
        lat: @place.latitude,
        lng: @place.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { place: @place }),
        marker_html: render_to_string(partial: "marker", locals: { place: @place })
      }
    ]
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    @place.user = current_user
    if @place.save
      redirect_to places_path
    else
      render :new, status: :unprocessable_entity # it didn t work properly to create a new place
    end
  end

  def edit
  end

  def update
    @place.photos.attach(params[:place][:photos])

    if @place.update(place_params)
      redirect_to place_path(@place)
    else
      render :edit
    end
  end

  def destroy
    if @place.destroy
      redirect_to places_path
    else
      render :index
    end
  end

  private

  def place_params
    params.require(:place).permit(:name, :details, :address, :header_photo, photos: [])
  end

  def set_place
    @place = Place.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_place
  before_action :authenticate_user!

  def index
    @reviews = Review.all
  end

  def edit
    if @review.user_id == current_user.id
      render :edit
    else
      redirect_to place_path(@place)
    end
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.place_id = @place.id

    if @review.save
      redirect_to @place
    else
      render :new
    end
  end

  def update
    @review.update(review_params)
  end

  def destroy
    @review.destroy
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def set_place
    @place = Place.find(params[:place_id])
  end

  def review_params
    params.require(:review).permit(:rating, :restroom_rating, :parking_rating, :other_rating, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def place_header_photo_url(place)
    if place.header_photo.attached?
      cl_image_path place.header_photo.key
    else
      image_url "Zurich_banner.webp"
    end
  end

  def profile_picture_url
    if current_user.avatar.attached?
      cloudinary_url current_user.avatar.key
    else
      image_url "avatar-unknown.png"
    end
  end

  def greeting_user
    time = Time.now
    if time.hour >= 5 && time.hour < 12
      "Good morning, #{current_user.first_name}!"
    elsif time.hour >= 12 && time.hour < 18
      "Good afternoon, #{current_user.first_name}!"
    else
      "Good Evening, #{current_user.first_name}!"
    end
  end

  def greeting_everyone
    time = Time.now
    if time.hour >= 5 && time.hour < 12
      "Good morning!"
    elsif time.hour >= 12 && time.hour < 18
      "Good afternoon!"
    else
      "Good Evening!"
    end
  end

def review_medals(total_reviews)
    if total_reviews >= 10 && total_reviews < 20
      "🥉"
    elsif total_reviews >= 20 && total_reviews < 30
      "🥈"
    elsif total_reviews >= 30 && total_reviews < 40
      "🥇"
    elsif total_reviews >= 40
      "🏵️"

    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accecity</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= favicon_link_tag "icon.png", rel: "icon", type: "image/png" %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="main-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="bg-light">
  <div class="container py-5">
    <div class="row h-100 align-items-center py-5">
      <div class="col-lg-6">
        <h1 class="display-4">About Accecity</h1>
        <p class="lead text-muted mb-0">Making the World Accessible.</p>
       </div>
      <div class="col-lg-6 d-none d-lg-block"><%= image_tag "accecity-about2.png", class:"img-fluid"%></div>
    </div>
  </div>
</div>

<div class="bg-white py-5">
  <div class="container py-5">
    <div class="row align-items-center mb-5">
      <div class="col-lg-6 order-2 order-lg-1"><i class="fa fa-bar-chart fa-2x mb-3 text-primary"></i>
        <h2 class="font-weight-light">We believe in a truly inclusive society</h2>
        <p class="font-italic text-muted mb-4">Ensuring accessibility for people using wheelchairs in public places is essential for creating a truly inclusive society. It promotes equal access to essential services, opportunities, and experiences, thereby fostering greater social integration and reducing stigma. By eliminating physical barriers and providing accessible pathways, we can create an environment where everyone can participate fully, regardless of their physical abilities. It is therefore crucial to prioritize accessibility in public spaces to promote inclusivity and diversity.</p>
      </div>
      <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><%= image_tag "accecity-about1.png", class:"img-fluid mb-4 mb-lg-0"%></div>
    </div>
    <div class="row align-items-center">
      <div class="col-lg-5 px-5 mx-auto"><%= image_tag "accecity-about3.png", class:"img-fluid mb-4 mb-lg-0"%></div>
      <div class="col-lg-6"><i class="fa-solid fa-star" style="color: orange"></i><i class="fa-solid fa-star" style="color: orange"></i><i class="fa-solid fa-star" style="color: orange"></i>
        <h2 class="font-weight-light">Rating places for accessibility </h2>
        <p class="font-italic text-muted mb-4">Rating places for accessibility is crucial in promoting greater inclusion and participation for people with disabilities. By providing feedback on the accessibility of public places, individuals can create awareness of the barriers they face, and bring attention to the need for change. This feedback can then be used by businesses, governments, and organizations to identify areas for improvement and implement solutions that promote accessibility.
        Sign up today und be a part of our community!</p><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary px-5 rounded-pill shadow-sm" %>
      </div>
    </div>
  </div>
</div>

<div class="bg-light py-5">
  <div class="container py-5">
    <div class="row mb-4">
      <div class="col-lg-5">
        <h2 class="display-4 font-weight-light">Our team</h2>
        <p class="font-italic text-muted">Our Accecity team is working towards a more inclusive and accessible society for all.</p>
      </div>
    </div>

    <div class="row text-center">

      <div class="col-xl-3 col-sm-6 mb-5">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="https://ca.slack-edge.com/T02NE0241-U04HLLL940P-f0c5b8e87dea-512" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">Diego Omegna</h5><span class="small text-uppercase text-muted"> Founder</span>
          <ul class="social mb-0 list-inline mt-3">
            <li class="list-inline-item"><a href="https://github.com/diegoOmegna" class="social-link"><i class="fa-brands fa-github"></i></a></li>
            <li class="list-inline-item"><a href="https://ch.linkedin.com/in/diego-omegna-676108262?trk=public_profile_browsemap" class="social-link"><i class="fa-brands fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>



      <div class="col-xl-3 col-sm-6 mb-5">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="https://ca.slack-edge.com/T02NE0241-U04HUQNBK2R-639e9db43118-512" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">Namgel Dorjee</h5><span class="small text-uppercase text-muted">Co - Founder</span>
          <ul class="social mb-0 list-inline mt-3">
            <li class="list-inline-item"><a href="https://github.com/dor-jee" class="social-link"><i class="fa-brands fa-github"></i></a></li>
            <li class="list-inline-item"><a href="https://linkedin.com/in/namgeldorjee" class="social-link"><i class="fa-brands fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>



      <div class="col-xl-3 col-sm-6 mb-5">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="https://ca.slack-edge.com/T02NE0241-U04JX8P33A5-f139545f7610-512" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">Karlo Malecki</h5><span class="small text-uppercase text-muted">Co - Founder</span>
          <ul class="social mb-0 list-inline mt-3">
            <li class="list-inline-item"><a href="https://github.com/Yoka225" class="social-link"><i class="fa-brands fa-github"></i></a></li>
            <li class="list-inline-item"><a href="https://www.linkedin.com/in/karlo-malecki-5b37698a/" class="social-link"><i class="fa-brands fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>


<%= render "shared/footer" %>

app/views/pages/home.html.erb
<div>
  <div class="home-headers">
    <div class="salute-header">
      <% if user_signed_in? %>
         <%= greeting_user %>
      <% else %>
        <%= greeting_everyone %>
      <% end %>
    </div>
    <div class="main-header">
      <h1>Where do you want to go today?</h1>
    </div>
  </div>
  <%= render "shared/banner" %>

  <div class="container">
    <div class="invitation">
      <h2>Join the community! </h2>
      <h3>Help us make the city a place for everyone,
      <%=link_to "Sign Up", new_user_registration_path %>
      and be part of the accessibility revolution.</h3>
      <h3>Find the all the information about accessibility
      for different places around your city. </h3>
      <h3>More about our goal and mission &#129351 <%= link_to "here", about_path %>.</h3>
    </div>
  </div>
    <div class="container">
      <div class="button-center" >
        <%= link_to "+Add New Place", new_place_path, class: "btn btn-primary" %>
      </div>
    </div>
  <div class="top-places">
  Top Rated Places
  </div>
  <%= render "shared/home_card" %>
  <%= render "shared/footer"  %>
</div>

app/views/pages/profile.html.erb
<section class="vh-100" style="background-color: orange;">
  <div class="container py-5 h-100 justify-content-center">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-6 mb-4 mb-lg-0">
        <div class="card mb-3" style="border-radius: .5rem;">
          <div class="row g-0">
            <div class="col-md-4 gradient-custom d-flex"
              style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">

                  <%= image_tag profile_picture_url, class: "avatar" %>

                    <div class="container mt-5">
                      <h3>
                          <% if user_signed_in? %>
                              <%= greeting_user %>
                          <% else %>
                            <%= greeting_everyone %>
                          <% end %>
                      </h3>

                        <div class="container">
                          <p>
                            <span class="text-muted small"> <%= review_medals(current_user.reviews.count) %> Reviews: <%= current_user.reviews.count %></span>
                          </p>
                         <% current_user.reviews do |review| %>
                           <%= review.rating %>
                         <% end %>
                        </div>
                    </div>

                      </div>
                      <div class="col-md-8">
                      <div class="card-body p-4">
                      <div class="Personal-popup">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                          Personal info
                        </button>
                      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLabel">Personal Info</h5>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                          <div class="modal-body">
                            <div class="container d-flex">
                              <p>First name:</p> <%= current_user.first_name %>
                            </div>
                            <div class="container d-flex">
                              <p>Last Name:</p> <%= current_user.last_name %>
                            </div>
                            <div class="container d-flex">
                              <p>e-mail:</p> <%= current_user.email %>
                            </div>
                          </div>

                          <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <%# <hr class="mt-0 mb-4"> %>
                  <div class="row pt-1">
                  <div class="col-6 mb-3">


                  <div class="container-review">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                      <h5>Reviews</h5>
                    </button>
                  </div>

                <div class="col-6 mb-3">
                </div>
                </div>
                </div>
                  <%# <hr class="mt-0 mb-4"> %>
                  <div class="row pt-1">
                  <div class="col-6 mb-3">
                    <div class="container">
                    <h6></h6>
                    <p class="text-muted"> </p>
                    </div>
                  </div>
                  <div class="col-6 mb-3">
                  </div>
                  </div>
                  <div class="btn btn-primary">
                    <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/places/_card.html.erb
<div class="card-product">
  <img src="https://picsum.photos/300/300?id=<%=place.id%>" />
  <div class="card-product-infos" >
    <h2><%= place.name%></h2>
    <p><%= place.details %> <br/> <br/> <strong><%= place.address %></strong>
      <br/> <br/>
      <div class="d-flex gap-1">
         <%= link_to "show", place_path(place), class:"btn btn-primary"%>
      </div>
    </p>
  </div>
</div>

app/views/places/_form.htm.erb
<%= simple_form_for(place) do |f| %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
<% end %>

<%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%>

app/views/places/_info_window.html.erb
<h2><%= place.name %></h2>
<p><%= place.address %></p>

app/views/places/_marker.html.erb
<%# <%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>

<div class="badge rounded-pill bg-primary fs-6">
  <%= place.name %>
</div>

app/views/places/edit.html.erb
<div class="container">
  <h1> Edit Place </h1>

  <%= simple_form_for @place do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :details %>
    <%= f.text_area :details, maxlength: 300, error: 'The text may not be longer than 300 Characters'%>
    <%= f.label :address %>
    <%= f.text_field :address %>
    <%= f.input :header_photo, as: :file, input_html: { multiple: false } %>
    <%= f.button :submit, "Update Place", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/places/index.html.erb
  <div class="container">
  <% if !user_signed_in? %>
    <div class="jumbotron p-3 shadow bg-light rounded">
      <h1>Your Favorite Places Reviewed</h1>
      <p>Please click Sign up button to review a place</p>
      <p><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
    </div>
  <% end %>

  <div class="container">
      <%= render "shared/form" %>
        <h1> Places </h1>
      <%= render "shared/cardsmall" %>
      <br>

    <%# <%= cl_image_tag("https://res.cloudinary.com/dtl8ilb2t/image/upload/v1678098172/cld-sample-2.jpg",
          width: 400, height: 300, crop: :fill) %>
      <%= link_to "Add New Place", new_place_path, class:"btn btn-primary" %>
      <%= link_to "Go Back", root_path, class:"btn btn-primary"%>
  </div>

<%= render "shared/footer" %>
</div>

app/views/places/new.html.erb
<div class="container">
    <% @place.errors.each do |error|%>
    <%= error.full_message %>
    <% end %>

    <div class="container">
      <div class="card mb-3 shadow">
      <%= image_tag "addplace.png", class:"card-img-top"%>
          <div class="card-body">
          <h5 class="card-title">Add a Place and help us to improve accessibility!</h5>
          <br>
          <%= simple_form_for @place do |f| %>
          <%= f.input :name %>
          <%= f.input :details, as: :text, maxlength: 300, error: 'The text may not be longer than 300 Characters' %>
          <%= f.input :zip_code %>
          <%= f.label :address %>
          <br/>
          <%= f.input :address, as: :hidden,
          input_html: { data: { address_autocomplete_target: "address" } },
          wrapper_html: { data: { controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"] } } %>
          <%= f.input :header_photo, as: :file, input_html: { multiple: false } %>
          <%= f.submit "Add Place", class: "btn btn-primary" %>
          <% end %>
          </div>
      </div>
    </div>
  <%= render "shared/footer" %>
</div>

app/views/places/show.html.erb
<style>
  .hidden {
    display: none;
  }
</style>

<div class="container">

  <%= render "/shared/card" %>


    <h2><strong>About Place</strong></h2>

         <p> <%= @place.details %> </p>
        <div class = "d-flex justify-content-between">
        <h2><strong><%= "Reviews (#{@reviews.length})" %></strong></h2>
        <h3><i class="fa-solid fa-star"></i> <%= @avg_review %></h3>
        </div>

    <div>
      <% counter = 0 %>
      <% @place.reviews.each do |review| %>
        <% if counter < 3 %>
          <div class="shadow p-3 mb-3 bg-white rounded">
            <p><%= review.user_first_name %></p>
            <p><strong>Entrance Rating </strong><% review.rating.to_i.times do  %>
              <i class="fa-solid fa-star"></i>
              <% end %></p>
            <p>Restroom Rating <% review.restroom_rating.to_i.times do  %>
              <i class="fa-solid fa-star"></i>
              <% end %></p>
            <p>Parking Rating <% review.parking_rating.to_i.times do  %>
              <i class="fa-solid fa-star"></i>
              <% end %></p>
            <p>Other Rating <% review.other_rating.to_i.times do  %>
              <i class="fa-solid fa-star"></i>
              <% end %></p>
            <p class="list-group-item"><%= review.comment %></p>
          </div>
          <% counter += 1 %>
        <% else %>
          <div class="shadow p-3 mb-3 bg-white rounded hidden">
            <p><%= review.user_first_name %></p>
            <p><strong>Entrance Rating </strong><% review.rating.to_i.times do  %>
              <i class="fa-solid fa-star"></i>
              <% end %></p>
            <p>Restroom Rating <% review.restroom_rating.to_i.times do  %>
              <i class="fa-solid fa-star"></i>
              <% end %></p>
            <p>Parking Rating <% review.parking_rating.to_i.times do  %>
              <i class="fa-solid fa-star"></i>
              <% end %></p>
            <p>Other Rating <% review.other_rating.to_i.times do  %>
              <i class="fa-solid fa-star"></i>
              <% end %></p>
            <p class="list-group-item"><%= review.comment %></p>
          </div>
        <% end %>
      <% end %>
      <% if @place.reviews.length > 3 %>
        <button id="show-more-btn" class="btn btn-primary">Show More Reviews</button>
      <% end %>
    </div>
    </div>


    <div class = "d-flex justify-content-center m-3">
        <%= link_to "+Add Review", new_place_review_path(@place), class: "btn btn-primary" %>
    </div>

    <div class="m-3">
      <h2><strong>Gallery Photo</strong></h2>
      <%= render "shared/photo_gallery" %>
        <%= simple_form_for @place, :action => 'update' do |f| %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.submit "Upload Photos", class: "btn btn-primary" %>
        <% end %>
    </div>
  <div class="justify-content-center m-3">
    <div class="mapbox">
      <div style="width: 95%; height: 600px;" data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

<script>
  document.getElementById("show-more-btn").addEventListener("click", function() {
    document.querySelectorAll(".hidden").forEach(function(review) {
      review.classList.remove("hidden");
    });
    this.style.display = "none";
  });
</script>

app/views/reviews/_form.html.erb
<div class="container">
  <h1>review</h1>
  <%= simple_form_for([@place, @review]) do |f| %>
    <%= f.input :rating %>
    <%= f.input :comment %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
  <%= link_to "Back", place_path(@place) %>
</div>

app/views/reviews/edit.html.erb
<div class="container">
  <h1>Edit review</h1>
  <%= simple_form_for([@place, @review]) do |f| %>
    <%= f.input :rating %>
    <%= f.input :comment %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
  <%= link_to "Back", place_path(@place) %>
</div>

app/views/shared/_form.html.erb
<%= form_with url: places_path, method: :get, class: "d-flex my-3" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a Place"
  %>
  <%= button_tag(type: "submit", class: "btn-form") do %>
    <i class="fa-solid fa-wheelchair-move"></i>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-no-background.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
          <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Places", places_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag profile_picture_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", profile_path , class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
             <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
            <%= link_to "About", about_path, class: "nav-link" %>
            </li>
             <li class="nav-item">
            <%= link_to "Places", places_path, class: "nav-link" %>
             </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>